In [1]:
# imports
%matplotlib notebook
import matplotlib.pyplot as plt
from camera import take_picture
import numpy as np
import csv

In [2]:
# download dlib models
from dlib_models import download_model, download_predictor, load_dlib_models
download_model()
download_predictor()
from dlib_models import models

File already exists:
	/Users/Jenny/Desktop/BWSI WORK/DlibModels/dlib_models/dlib_face_recognition_resnet_model_v1.dat
File already exists:
	/Users/Jenny/Desktop/BWSI WORK/DlibModels/dlib_models/shape_predictor_68_face_landmarks.dat


In [3]:
load_dlib_models()
face_detect = models["face detect"]
shape_predictor = models["shape predict"]

In [17]:
import pathlib
import skimage.io as io

def readfiles(path1): 
    emote = list()
    img = list()
    with open(pathlib.Path(path1+'/details.csv'), newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
        for row in spamreader:
            row1 = row[1].split(',')
            emote.append(row1[2])
            path=pathlib.Path(path1)/row1[1][1:len(row1[1])-1]
            img.append(io.imread(path))
            #img.append((open(row1[1]),'r+').read())
        #emote = [row[1].split(',')[2] for row in spamreader]
        #img = open('photo.jpg', 'r+')
    return np.array(emote), np.array(img)
                 
"""
    with open(filename, mode='r') as file:
        return int(float(file.read().split()[0]))
"""

emotions, imgs = readfiles('/Users/Jenny/Desktop/BWSI WORK/ISED_database')

In [18]:
print(emotions[:10])
print(imgs[:10])

['1' '1' '1' '1' '3' '4' '4' '4' '1' '1']
[[[[ 53  35  25]
   [ 68  50  40]
   [ 78  60  48]
   ...
   [ 53  41  25]
   [ 42  33  16]
   [ 35  26  11]]

  [[ 75  57  47]
   [ 93  75  65]
   [106  88  76]
   ...
   [ 71  60  42]
   [ 58  49  32]
   [ 49  40  25]]

  [[ 88  70  58]
   [108  90  78]
   [125 107  93]
   ...
   [ 87  76  58]
   [ 71  63  44]
   [ 61  52  35]]

  ...

  [[ 82  74  55]
   [ 98  87  67]
   [120 107  88]
   ...
   [103  86  66]
   [ 90  73  53]
   [ 73  56  38]]

  [[ 65  56  39]
   [ 79  68  50]
   [ 97  84  65]
   ...
   [ 87  70  52]
   [ 77  60  42]
   [ 62  45  29]]

  [[ 43  34  17]
   [ 55  43  27]
   [ 71  58  41]
   ...
   [ 63  46  30]
   [ 56  39  23]
   [ 44  26  12]]]


 [[[ 57  39  19]
   [ 70  52  32]
   [ 79  61  39]
   ...
   [ 53  42  20]
   [ 46  38  17]
   [ 35  27   8]]

  [[ 77  59  39]
   [ 93  75  53]
   [105  87  63]
   ...
   [ 75  64  42]
   [ 68  57  37]
   [ 54  46  25]]

  [[ 97  79  57]
   [115  97  75]
   [131 113  89]
   ...
   